### ISSUE TITLE
Mob change their name to unknown when tamed

### ISSUE THREAD

**Issue by Dynosawr** [ANightDazingZoroark/Prehistoric-Rift-Addon#107]
This is a bug

**Comment by ANightDazingZoroark** [comment]
all tamed modded mobs in minecraft bedrock are called unknown, cannot fix because thats a minecraft bug :/

**Comment by ANightDazingZoroark** [comment]
just checked with the fallen kingdom addon, and yes, tamed creatures from that addon are also called unknown
