### ISSUE TITLE
Unable to tame Dino’s on mobile

### ISSUE THREAD

**Issue by NathanVanVelden** [ANightDazingZoroark/Prehistoric-Rift-Addon#137]
Hello so it is not possible to craft treats on mobile it is also not possible to obtain those by cheats or the creative menu which means mobile players are unable to tame any dinosaurs please add a mobile support and fix this issue

**Comment by ANightDazingZoroark** [comment]
try this out, it works on mobile btw https://prehistoric-rift.fandom.com/wiki/Troubleshooting

**Comment by ANightDazingZoroark** [comment]
ywk just in case this poor kid decides to come back imma reopen

**Comment by ANightDazingZoroark** [comment]
ye theres no way this kid is gonna come back
