### ISSUE TITLE
stego plates should be thicker

### ISSUE THREAD

**Issue by ANightDazingZoroark** [ANightDazingZoroark/Prehistoric-Rift-Addon#15]
at this point in time this should have been a thing; especially since the thin plates look unrealistic

**Comment by DTRaptor** [comment]
Ok, but just be careful not to make it stand out from the rest of the model.

**Comment by ANightDazingZoroark** [comment]
![stegosaurus rift](https://user-images.githubusercontent.com/56536620/70842466-0605ef00-1e5f-11ea-957e-9bb44ea5a814.png)
yeet, thicc plates
