### ISSUE TITLE
tyrannosaurus' head is sort of cut off from its body

### ISSUE THREAD

**Issue by ANightDazingZoroark** [ANightDazingZoroark/Prehistoric-Rift-Addon#6]

**Comment by ANightDazingZoroark** [comment]
![image](https://user-images.githubusercontent.com/56536620/70384726-a15e1680-19be-11ea-9fb8-4043194b084e.png)

**Comment by DTRaptor** [comment]
There's something wrong with the model, animation or rendering.

**Comment by ANightDazingZoroark** [comment]
even though this is fixed, i might have to deal with this again when dealing with animations not being displayed
