### ISSUE TITLE
stegosaurus's plates are surrounded with black stuff

### ISSUE THREAD

**Issue by ANightDazingZoroark** [ANightDazingZoroark/Prehistoric-Rift-Addon#7]

**Comment by ANightDazingZoroark** [comment]
![image](https://user-images.githubusercontent.com/56536620/70384737-cfdbf180-19be-11ea-8fb3-7a1619db94b4.png)

**Comment by DTRaptor** [comment]
There's something wrong with the texturing or rendering.

**Comment by ANightDazingZoroark** [comment]
its must be the model, might have to edit the model and textures later

**Comment by ANightDazingZoroark** [comment]
making the plates thicc solved this issue as well
