### ISSUE TITLE
trike spawning crashes the game

### ISSUE THREAD

**Issue by ANightDazingZoroark** [ANightDazingZoroark/Prehistoric-Rift-Addon#81]
only in beta 1.16.100.51

**Comment by ANightDazingZoroark** [comment]
ok, turns out that its because it was using the `entity_alphablend` material, which in the latest beta crashes the fucking game. i could try changing the quills to fix this tho

**Comment by ANightDazingZoroark** [comment]
lmao i could wait for next beta to fix this but im lazy so whatever

**Comment by ANightDazingZoroark** [comment]
fixxed

**Comment by CoFuture** [comment]
Hello, i have the same problem. Game crushed when i try to spawn an entity with **entity_alphablend** material. Could you please tell me how to fix this problem?

**Comment by ANightDazingZoroark** [comment]
> 
> 
> Hello, i have the same problem. Game crushed when i try to spawn an entity with **entity_alphablend** material. Could you please tell me how to fix this problem?

change the material to `skeleton`

**Comment by CoFuture** [comment]
> > Hello, i have the same problem. Game crushed when i try to spawn an entity with **entity_alphablend** material. Could you please tell me how to fix this problem?
> 
> change the material to `skeleton`

Thanks bro
